name: Generate ProtoBuf Files

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Generator Repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Install Protobuf Compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - name: Install Go Protobuf Tools
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

      - name: Clone Proto Files Repository
        run: |
          git clone https://github.com/shynggys9219/ap2-apis-user-service.git
          cd proto-files

      - name: Generate Go Code from Proto Files
        run: |
          mkdir -p generated
          protoc --go_out=./generated --go-grpc_out=./generated $(find . -name "*.proto")

      - name: Push Generated Files
        run: |
          cd generated
          git init
          git checkout -b generated-files
          git add .
          git commit -m "Generated files from Protobufs"
          git remote add origin https://github.com/shynggys9219/ap2-apis-gen-user-service.git
          git push -u origin generated-files --force
