name: Generate ProtoBuf Files & Auto Tag

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Generator Repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Install Protobuf Compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - name: Install Go Protobuf Tools
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

      - name: Clone Proto Files Repository
        run: |
          git clone https://github.com/shynggys9219/ap2-apis-user-service.git
          cd ap2-apis-user-service

      - name: Generate Go Code from Proto Files
        run: |
          cd ap2-apis-user-service

          # Confirm directory structure
          echo "Directory structure before generation:"
          find . -type d

          # Remove old generated files to avoid mixing
          rm -rf base/bo/v1 service/frontend/client/v1

          # Recreate directories for generated files
          mkdir -p base/bo/v1
          mkdir -p service/frontend/client/v1

          # Verify .proto files are where we expect them to be
          echo "Listing all .proto files:"
          find . -name "*.proto"

          # Make sure the .proto files actually exist
          if [ ! -f "base/frontend/v1/client.proto" ]; then
            echo "Error: base/frontend/v1/client.proto not found."
            exit 1
          fi

          if [ ! -f "service/frontend/client/v1/client.proto" ]; then
            echo "Error: service/frontend/client/v1/client.proto not found."
            exit 1
          fi

          # Generate base files (messages) from proto in `base/frontend/v1`
          echo "Generating base files..."
          protoc -I. \
            --go_out=paths=source_relative:base/bo/v1 \
            base/frontend/v1/client.proto

          # Generate service files (messages + grpc services) from proto in `service/frontend/client/v1`
          echo "Generating service files..."
          protoc -I. \
            --go_out=paths=source_relative:service/frontend/client/v1 \
            --go-grpc_out=paths=source_relative:service/frontend/client/v1 \
            service/frontend/client/v1/client.proto

          # Verify generated files
          echo "Generated Go files:"
          find base service -name "*.pb.go" || echo "No files generated"

          # Ensure files are generated
          if [ -z "$(find base service -name "*.pb.go")" ]; then
            echo "Error: No .pb.go files generated."
            exit 1
          fi

      - name: Verify Generated Files
        run: |
          cd ap2-apis-user-service
          ls -R base || echo "Base directory not found"
          ls -R service || echo "Service directory not found"

      - name: Commit & Push Generated Files
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          cd ap2-apis-user-service

          # Clone the target repository
          git clone https://github.com/shynggys9219/ap2-apis-gen-user-service.git

          # Copy generated files into the cloned repo (force overwrite)
          rsync -av --delete base/ ap2-apis-gen-user-service/base/
          rsync -av --delete service/ ap2-apis-gen-user-service/service/

          cd ap2-apis-gen-user-service

          # Remove all .proto files before committing
          find . -name "*.proto" -delete

          git config --global user.name "shynggys9219"
          git config --global user.email "alshynggys@mail.ru"

          git add .
          git commit -m "Generated files from Protobufs"
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/shynggys9219/ap2-apis-gen-user-service.git
          git push origin master
