name: Generate ProtoBuf Files & Auto Tag

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Generator Repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Install Protobuf Compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - name: Install Go Protobuf Tools
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

      - name: Clone Proto Files Repository
        run: |
          git clone https://github.com/shynggys9219/ap2-apis-user-service.git
          cd ap2-apis-user-service

      - name: Generate Go Code from Proto Files
        run: |
          cd ap2-apis-user-service

          # Remove old generated files to avoid mixing
          rm -rf base service

          # Create base and service directories if they do not exist
          mkdir -p base/bo/v1 service/frontend/client/v1

          # Generate base files (messages) directly into base/bo/v1
          find . -name "*.proto" -exec protoc --proto_path=. \
            --go_out=paths=source_relative:base/bo/v1 {} +

          # Generate service files (services) directly into service/frontend/client/v1
          find . -name "*.proto" -exec protoc --proto_path=. \
            --go-grpc_out=paths=source_relative:service/frontend/client/v1 {} +
      
      

      - name: Verify Generated Files
        run: |
          cd ap2-apis-user-service
          ls -R base || echo "Base directory not found"
          ls -R service || echo "Service directory not found"

      - name: Commit & Push Generated Files
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          cd ap2-apis-user-service
          
          # Check if base and service directories exist before copying
          if [ ! -d "base" ] || [ ! -d "service" ]; then
            echo "Base or Service directory not found, generation failed."
            exit 1
          fi
          
          # Clone the target repository
          git clone https://github.com/shynggys9219/ap2-apis-gen-user-service.git
          
          # Copy generated files into the cloned repo
          cp -r base service ap2-apis-gen-user-service/
          
          cd ap2-apis-gen-user-service
          git config --global user.name "shynggys9219"
          git config --global user.email "alshynggys@mail.ru"
          git add .
          
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          
          git commit -m "Generated files from Protobufs"
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/shynggys9219/ap2-apis-gen-user-service.git
          git push origin master
