name: Generate ProtoBuf Files & Auto Tag

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Generator Repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Install Protobuf Compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - name: Install Go Protobuf Tools
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

      - name: Clone Proto Files Repository
        run: |
          git clone https://github.com/shynggys9219/ap2-apis-user-service.git

      - name: Generate Go Code from Proto Files
        run: |
          cd ap2-apis-user-service
          
          # Remove old generated files to avoid mixing
          rm -rf base service
          
          # Create base and service directories if they do not exist
          mkdir -p base/bo/v1 service/frontend/client/v1
          
          # Generate base files (messages) directly into base/bo/v1
          find . -name "*.proto" -exec protoc -I. \
            --go_out=base/bo/v1 {} \;

          # Generate service files (services) directly into service/frontend/client/v1
          find . -name "*.proto" -exec protoc -I. \
            --go-grpc_out=service/frontend/client/v1 {} \;

          echo "Generated Go files:"
          find base service -type f

      - name: Commit & Push Generated Files
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          # Clone the target repository
          git clone https://github.com/shynggys9219/ap2-apis-gen-user-service.git

          # Copy generated files into the cloned repo
          rsync -av --delete ap2-apis-user-service/base/ ap2-apis-gen-user-service/base/
          rsync -av --delete ap2-apis-user-service/service/ ap2-apis-gen-user-service/service/

          cd ap2-apis-gen-user-service

          git config --global user.name "shynggys9219"
          git config --global user.email "alshynggys@mail.ru"

          git add .

          if git diff --cached --quiet; then
            echo "No changes to commit in generated files."
            exit 0
          fi

          git commit -m "Generated files from Protobufs"
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/shynggys9219/ap2-apis-gen-user-service.git
          git push origin master
